---
resources:
  - name: db_source_files
    type: git
    source: {uri: agapebondservant/noblenmrodb, skip-ssl-verification: true}
  - name: db_deployment_files
    type:  git
    source: {uri: agapebondservant/noblenmro, skip-ssl-verification: true}
  - name: db_client
    type: docker-image
    source: {repository: oawofolu2/oracleinstantclient, tag: "v1.0"}

jobs:
  name: deploy_db
  public: true
  plan:
    - get: db_source_files
    - get: db_deployment_files
    - get: db_client
      params: {save: true}
    - task: deploy
      config:
        platform: linux
        run:
          path: ls
          args: [-alR]
