---
jobs:
  name: deploy_db
  public: true
  plan:
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: oawofolu2/ifsdb, tag: "1.0"}
        run:
          path: echo
          args:
          - hello world
