---
resources:
- name: db_source_files
  type: git
  source: 
    uri: https://github.com/agapebondservant/noblenmrodb.git
    skip-ssl-verification: true
- name: db_deployment_files
  type:  git
  source: 
    uri: https://github.com/agapebondservant/noblenmro.git
    skip-ssl-verification: true
- name: db_log_files
  type: s3
  source:
    bucket: ((logfilebucket))
    regexp: ([0-9]+)_.*_logs.zip
    access_key_id: ((accesskey))
    secret_access_key: ((secret))

jobs:
- name: deploy_db
  public: true
  plan:
  - get: db_source_files
  - get: db_deployment_files
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: oawofolu2/oracleinstantclient, tag: "v1.0"}
      inputs:
        - name: db_source_files
        - name: db_deployment_files
      outputs:
        - name: db_logs
      run:
        path: ./db_deployment_files/scripts/deploydb.sh
        args: []
      params:
        USERNAME: ((username))
        PASSWD: ((passwd))
        HOST: ((host))
        SID: ((sid))
  - put: db_log_files
    params:
      path: ./db_logs/*.zip  

